### ISSUE TITLE
Can we change a time for Timeout?

### ISSUE THREAD

**Issue by Kondzolko** [infosimples/anti_captcha#3]
Hi, thank you for your gem, looks very good, but sometimes I have error "Caused by Net::ReadTimeout: Net::ReadTimeout"

Can we change TImeout for a little bit longer because some time is not enough time to get a response from anti-captcha service?

Thank you

**Comment by rafaelivan** [comment]
Hello, @Kondzolko.

Yes, you can set a greater timeout if you want.

`client = AntiCaptcha.new('my_key', timeout: 120)`

The default timeout is 60 seconds.

**Comment by acrogenesis** [comment]
Do you know if we are getting charged for the timeouts?

**Comment by barbolo** [comment]
Yes. You might be charged for timeouts. The timeouts are set on client side (your ruby process) not on server (anticaptcha API)
