### ISSUE TITLE
💩‼️ This company anti-captcha.com is a scam

### ISSUE THREAD

**Issue by ZenImagine** [infosimples/anti_captcha#8]
💩‼️ This company is a scam, it is the owner of anti-captcha.com and refuses to modify or delete your personal data. Customer support insults you and the site has already been hacked multiple times. If you are a customer, do not hesitate to report actionfraud.police.uk

https://ibb.co/ZX3t4S4

**Comment by barbolo** [comment]
What do you want us to do? This gem is open source and is not maintained by AntiCaptcha themselves.

**Comment by ZenImagine** [comment]
Only here can I get the attention of this con artist. He drained my account balance and blocked requests for assistance. I know myself but it is impossible for me to modify my email.
If you know this fool, please contact him urgently.

**Comment by barbolo** [comment]
We don't have the contact of anyone who works at AntiCaptcha. I'm sorry for your situation and I hope you can solve your issue directly with them. I'd like to ask you, gently, to stop opening issues in this repository. Thank you.
